### PR TITLE
fix(slack): use fixed section order when generating changelog

### LINKED ISSUE #244: Slack output has different order to normal releases
The order should be:
- Features
- Bugfixes
- Chores and Improvements
- Other

Currently it's a bit random

### PR DESCRIPTION
**Pull request by aexvir**
closes #244

### CODE REVIEW

File: internal/slack/release_notes.go [hunk 1]
```diff
@@ -75,6 +77,8 @@ func GenerateReleaseNotes(sections map[string][]quoad.Commit, remote GitRemoter)
 			currentSection++
 		}
 	}
+	data, _ := json.Marshal(blocks)
+	fmt.Println(string(data))
```
Comment (fallion) [inline internal/slack/release_notes.go:81]: Is this for debugging?

Comment (aexvir) [reply internal/slack/release_notes.go:81]: oops, yeah :D

**Review by fallion — APPROVED** [review]
